#!/usr/bin/env python3
"""Regenerates SplashLogoPaths.swift from the app icon artwork.

SwiftDraw emits a Canvas-drawing view, but the splash needs the outlines as
standalone `Path` values so each one can be trimmed independently. The path
construction inside that output is already separated per shape, so this lifts
those blocks out and drops the drawing calls around them.

Usage: tools/generate-splash-paths.py
Requires: brew install swiftdraw
"""

import re
import subprocess
import textwrap
import sys
import tempfile
from pathlib import Path as FilePath

ROOT = FilePath(__file__).resolve().parent.parent
SVG = ROOT / "AppIcon.icon" / "Assets" / "icon.svg"
OUT = ROOT / "src" / "App" / "SplashLogoPaths.swift"

# Names follow icon.svg document order. Reordering the SVG means reordering this
# list — the splash animates them in a different order, chosen in SplashView.
PATH_NAMES = ["hook", "diagonal", "arc"]

VIEW_BOX = re.compile(r'viewBox="0 0 (\d+(?:\.\d+)?) (\d+(?:\.\d+)?)"')
BLOCK = re.compile(
    r"let (path\d*) = CGMutablePath\(\)\n(.*?)\n\s*ctx\.addPath\(\1\)",
    re.DOTALL,
)


def main() -> int:
    if not SVG.exists():
        sys.exit(f"artwork not found: {SVG}")

    box = VIEW_BOX.search(SVG.read_text())
    if not box:
        sys.exit("could not read viewBox from the artwork")
    if box.group(1) != box.group(2):
        sys.exit(f"expected a square viewBox, got {box.group(1)}x{box.group(2)}")
    view_box = box.group(1)

    with tempfile.NamedTemporaryFile(suffix=".swift") as tmp:
        try:
            subprocess.run(
                ["swiftdraw", str(SVG), "--format", "swift",
                 "--api", "swiftui", "--output", tmp.name],
                check=True, capture_output=True, text=True,
            )
        except FileNotFoundError:
            sys.exit("swiftdraw not on PATH — install it with: brew install swiftdraw")
        except subprocess.CalledProcessError as error:
            sys.exit(f"swiftdraw failed:\n{error.stderr}")
        generated = FilePath(tmp.name).read_text()

    blocks = BLOCK.findall(generated)
    if len(blocks) != len(PATH_NAMES):
        sys.exit(
            f"artwork has {len(blocks)} shapes but PATH_NAMES lists "
            f"{len(PATH_NAMES)} — update the list and the splash animation order"
        )

    parts = [
        "// Generated by tools/generate-splash-paths.py — do not edit by hand.",
        f"// Source: {SVG.relative_to(ROOT)}",
        "",
        "import CoreGraphics",
        "import SwiftUI",
        "",
        "/// Logo outlines lifted from the app icon artwork, in its own coordinate space.",
        "enum SplashLogoPaths {",
        f"    /// The artwork's viewBox, so callers can scale into any frame.",
        f"    static let viewBox: CGFloat = {view_box}",
    ]

    for name, (symbol, body) in zip(PATH_NAMES, blocks):
        # dedent as a block so wrapped control-point arguments keep their alignment
        block = re.sub(rf"\b{symbol}\.", "path.", textwrap.dedent(body).strip())
        parts += ["", f"    static let {name}: Path = {{", "        let path = CGMutablePath()"]
        parts += [f"        {line}" if line else "" for line in block.splitlines()]
        parts += ["        return Path(path)", "    }()"]

    parts += ["}", ""]
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT.relative_to(ROOT)} ({len(blocks)} paths, viewBox {view_box})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
