modules:
  - android-app
  - ios-app
  - jvm-app
  - shared
  - shared/api
  - shared/data
  - shared/domain
  - shared/ui/design-system
  - shared/ui/feature/home
  - shared/ui/feature/title
  - shared/ui/feature/profile