// Generated by tools/generate-splash-paths.py — do not edit by hand.
// Source: AppIcon.icon/Assets/icon.svg

import CoreGraphics
import SwiftUI

/// Logo outlines lifted from the app icon artwork, in its own coordinate space.
enum SplashLogoPaths {
    /// The artwork's viewBox, so callers can scale into any frame.
    static let viewBox: CGFloat = 1174

    static let hook: Path = {
        let path = CGMutablePath()
        path.move(to: CGPoint(x: 698, y: 245))
        path.addCurve(to: CGPoint(x: 712, y: 236),
                       control1: CGPoint(x: 698, y: 238),
                       control2: CGPoint(x: 706, y: 233))
        path.addLine(to: CGPoint(x: 881, y: 313))
        path.addCurve(to: CGPoint(x: 887, y: 322),
                       control1: CGPoint(x: 885, y: 315),
                       control2: CGPoint(x: 887, y: 319))
        path.addLine(to: CGPoint(x: 887, y: 717))
        path.addCurve(to: CGPoint(x: 897, y: 727),
                       control1: CGPoint(x: 887, y: 723),
                       control2: CGPoint(x: 891, y: 727))
        path.addLine(to: CGPoint(x: 1145, y: 727))
        path.addCurve(to: CGPoint(x: 1154, y: 739),
                       control1: CGPoint(x: 1151, y: 727),
                       control2: CGPoint(x: 1156, y: 733))
        path.addCurve(to: CGPoint(x: 1013.3, y: 990.5),
                       control1: CGPoint(x: 1128.7, y: 833.2),
                       control2: CGPoint(x: 1080.4, y: 919.7))
        path.addCurve(to: CGPoint(x: 769.8, y: 1144.7),
                       control1: CGPoint(x: 946.2, y: 1061.4),
                       control2: CGPoint(x: 862.5, y: 1114.4))
        path.addCurve(to: CGPoint(x: 482.3, y: 1164.5),
                       control1: CGPoint(x: 677.1, y: 1175.1),
                       control2: CGPoint(x: 578.3, y: 1181.9))
        path.addCurve(to: CGPoint(x: 220, y: 1045),
                       control1: CGPoint(x: 386.3, y: 1147.1),
                       control2: CGPoint(x: 296.1, y: 1106))
        path.addCurve(to: CGPoint(x: 218, y: 1033),
                       control1: CGPoint(x: 217, y: 1042),
                       control2: CGPoint(x: 216, y: 1037))
        path.addLine(to: CGPoint(x: 252, y: 975))
        path.addCurve(to: CGPoint(x: 267, y: 972),
                       control1: CGPoint(x: 255, y: 970),
                       control2: CGPoint(x: 262, y: 968))
        path.addCurve(to: CGPoint(x: 442.4, y: 1066.9),
                       control1: CGPoint(x: 318.5, y: 1015.1),
                       control2: CGPoint(x: 378.1, y: 1047.4))
        path.addCurve(to: CGPoint(x: 640.9, y: 1085.6),
                       control1: CGPoint(x: 506.6, y: 1086.5),
                       control2: CGPoint(x: 574.1, y: 1092.8))
        path.addCurve(to: CGPoint(x: 830.9, y: 1025.1),
                       control1: CGPoint(x: 707.6, y: 1078.4),
                       control2: CGPoint(x: 772.3, y: 1057.8))
        path.addCurve(to: CGPoint(x: 982, y: 895),
                       control1: CGPoint(x: 889.5, y: 992.3),
                       control2: CGPoint(x: 940.9, y: 948.1))
        path.addCurve(to: CGPoint(x: 974, y: 879),
                       control1: CGPoint(x: 987, y: 888),
                       control2: CGPoint(x: 983, y: 879))
        path.addLine(to: CGPoint(x: 881, y: 879))
        path.addCurve(to: CGPoint(x: 872, y: 874),
                       control1: CGPoint(x: 877, y: 879),
                       control2: CGPoint(x: 874, y: 877))
        path.addLine(to: CGPoint(x: 699, y: 574))
        path.addLine(to: CGPoint(x: 698, y: 569))
        path.closeSubpath()
        return Path(path)
    }()

    static let diagonal: Path = {
        let path = CGMutablePath()
        path.move(to: CGPoint(x: 422, y: 240))
        path.addCurve(to: CGPoint(x: 440, y: 240),
                       control1: CGPoint(x: 426, y: 233),
                       control2: CGPoint(x: 436, y: 233))
        path.addLine(to: CGPoint(x: 800, y: 864))
        path.addCurve(to: CGPoint(x: 792, y: 879),
                       control1: CGPoint(x: 804, y: 871),
                       control2: CGPoint(x: 799, y: 879))
        path.addLine(to: CGPoint(x: 628, y: 879))
        path.addCurve(to: CGPoint(x: 619, y: 874),
                       control1: CGPoint(x: 624, y: 879),
                       control2: CGPoint(x: 621, y: 877))
        path.addLine(to: CGPoint(x: 576, y: 799))
        path.addCurve(to: CGPoint(x: 567, y: 794),
                       control1: CGPoint(x: 574, y: 796),
                       control2: CGPoint(x: 571, y: 794))
        path.addLine(to: CGPoint(x: 373, y: 794))
        path.addCurve(to: CGPoint(x: 365, y: 779),
                       control1: CGPoint(x: 366, y: 794),
                       control2: CGPoint(x: 361, y: 786))
        path.addLine(to: CGPoint(x: 430, y: 666))
        path.addCurve(to: CGPoint(x: 438, y: 661),
                       control1: CGPoint(x: 431, y: 663),
                       control2: CGPoint(x: 435, y: 661))
        path.addLine(to: CGPoint(x: 479, y: 661))
        path.addCurve(to: CGPoint(x: 487, y: 646),
                       control1: CGPoint(x: 486, y: 661),
                       control2: CGPoint(x: 491, y: 653))
        path.addLine(to: CGPoint(x: 440, y: 563))
        path.addCurve(to: CGPoint(x: 422, y: 563),
                       control1: CGPoint(x: 436, y: 556),
                       control2: CGPoint(x: 426, y: 556))
        path.addLine(to: CGPoint(x: 211, y: 929))
        path.addLine(to: CGPoint(x: 211, y: 930))
        path.addLine(to: CGPoint(x: 188, y: 969))
        path.addLine(to: CGPoint(x: 187, y: 970))
        path.addLine(to: CGPoint(x: 177, y: 989))
        path.addCurve(to: CGPoint(x: 161, y: 991),
                       control1: CGPoint(x: 173, y: 995),
                       control2: CGPoint(x: 165, y: 996))
        path.addCurve(to: CGPoint(x: 69, y: 863),
                       control1: CGPoint(x: 125, y: 953),
                       control2: CGPoint(x: 94, y: 909))
        path.addCurve(to: CGPoint(x: 69, y: 853),
                       control1: CGPoint(x: 67, y: 860),
                       control2: CGPoint(x: 67, y: 856))
        path.addLine(to: CGPoint(x: 79, y: 834))
        path.addLine(to: CGPoint(x: 81, y: 832))
        path.addLine(to: CGPoint(x: 81, y: 831))
        path.closeSubpath()
        return Path(path)
    }()

    static let arc: Path = {
        let path = CGMutablePath()
        path.move(to: CGPoint(x: 587, y: 0))
        path.addCurve(to: CGPoint(x: 828.3, y: 52.1),
                       control1: CGPoint(x: 670.2, y: 0.1),
                       control2: CGPoint(x: 752.5, y: 17.8))
        path.addCurve(to: CGPoint(x: 1026.8, y: 198.8),
                       control1: CGPoint(x: 904.1, y: 86.4),
                       control2: CGPoint(x: 971.8, y: 136.3))
        path.addCurve(to: CGPoint(x: 1147.5, y: 414.1),
                       control1: CGPoint(x: 1081.9, y: 261.2),
                       control2: CGPoint(x: 1123, y: 334.6))
        path.addCurve(to: CGPoint(x: 1169, y: 660),
                       control1: CGPoint(x: 1172, y: 493.6),
                       control2: CGPoint(x: 1179.3, y: 577.4))
        path.addCurve(to: CGPoint(x: 1160, y: 669),
                       control1: CGPoint(x: 1169, y: 665),
                       control2: CGPoint(x: 1165, y: 669))
        path.addLine(to: CGPoint(x: 1093, y: 669))
        path.addCurve(to: CGPoint(x: 1083, y: 657),
                       control1: CGPoint(x: 1087, y: 669),
                       control2: CGPoint(x: 1082, y: 663))
        path.addCurve(to: CGPoint(x: 960.5, y: 252.5),
                       control1: CGPoint(x: 1103.8, y: 510.7),
                       control2: CGPoint(x: 1059, y: 362.7))
        path.addCurve(to: CGPoint(x: 572.3, y: 85.6),
                       control1: CGPoint(x: 862.1, y: 142.4),
                       control2: CGPoint(x: 720, y: 81.3))
        path.addCurve(to: CGPoint(x: 194.5, y: 275),
                       control1: CGPoint(x: 424.6, y: 90),
                       control2: CGPoint(x: 286.3, y: 159.3))
        path.addCurve(to: CGPoint(x: 96, y: 686),
                       control1: CGPoint(x: 102.7, y: 390.8),
                       control2: CGPoint(x: 66.6, y: 541.2))
        path.addLine(to: CGPoint(x: 95, y: 693))
        path.addLine(to: CGPoint(x: 48, y: 774))
        path.addCurve(to: CGPoint(x: 30, y: 772),
                       control1: CGPoint(x: 43, y: 781),
                       control2: CGPoint(x: 33, y: 780))
        path.addCurve(to: CGPoint(x: 6.4, y: 497.8),
                       control1: CGPoint(x: 0.5, y: 683.8),
                       control2: CGPoint(x: -7.6, y: 589.8))
        path.addCurve(to: CGPoint(x: 110.5, y: 243.1),
                       control1: CGPoint(x: 20.4, y: 405.9),
                       control2: CGPoint(x: 56, y: 318.6))
        path.addCurve(to: CGPoint(x: 319.4, y: 64),
                       control1: CGPoint(x: 164.9, y: 167.7),
                       control2: CGPoint(x: 236.5, y: 106.3))
        path.addCurve(to: CGPoint(x: 587, y: 0),
                       control1: CGPoint(x: 402.2, y: 21.7),
                       control2: CGPoint(x: 494, y: -0.2))
        path.closeSubpath()
        return Path(path)
    }()
}
